language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --dev --prefer-source
  
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq notify-osd

script: php vendor/bin/phpspec run --format=dot
